version: '3.9'
services:
  webserver:
    container_name: PHP-webServer 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes: 
      - ./www:/var/www/html

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
